### ISSUE TITLE
singInWithPhoneNumber failed: Expected 2 arguments but got 1.

### ISSUE THREAD

**Issue by raboija** [amandeepmittal/rnPhoneAuthDemo#6]
How did you get past this? Most other tutorials implements/uses an app validator some host by themselves for CAPTCHA, but I liked your code its very simplistic. How did you not get this issue in your screenshots. Since my code is super similar to your implementation.

**Comment by raboija** [comment]
![screenshot_20200518-120928](https://user-images.githubusercontent.com/47260800/82211882-1f750080-9901-11ea-8489-45b9efc0827c.png)

**Comment by raboija** [comment]
Tested in Google Pixel 2 XL Android 10 with Expo CLI.

**Comment by amandeepmittal** [comment]
I think, we've discussed this over email and please note that in the demo, I am not using Expo CLI. Thus, I am closing this issue.

**Comment by sopu0000** [comment]
I also got same error , please explain it to me
